# Generated by Django 4.0.3 on 2022-12-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_technicianvo_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appointment_date_time',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='automobile',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
