# Generated by Django 4.0.3 on 2022-12-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0008_remove_serviceappointment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceappointment",
            name="completed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
