# Generated by Django 4.0.3 on 2022-12-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0010_remove_serviceappointment_automobile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceappointment",
            name="status",
        ),
    ]
