# Generated by Django 4.0.3 on 2022-12-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_remove_serviceappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
